name:                snap
version:             0.1.0.0
github:              "branjwong/snap"
license:             BSD3
author:              "Brandon Wong"
maintainer:          "branjwong@gmail.com"
copyright:           "Copyright (c) 2020 Brandon Wong"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Test

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/branjwong/snap#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  snap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snap

tests:
  snap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snap
